---
- name: Launch AWS EC2 instances
  hosts: localhost
  connection: local
  gather_facts: true
  tags:
  - launch
  tasks:
  - name: Launch instances
    ec2:
      count_tag:
        ansible_group: "{{ aws_ansible_group_tag }}"
      exact_count: "{{ aws_instance_count }}"
      group: "{{ aws_security_group }}"
      image: "{{ aws_ami }}"
      instance_tags:
        ansible_group: "{{ aws_ansible_group_tag }}"
      instance_type: "{{ aws_instance_type }}"
      key_name: "{{ aws_key }}"
      region: "{{ aws_region }}"
      wait: true
    register: ec2

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      timeout: 120
      state: started
    with_items: "{{ ec2.tagged_instances }}"

  - name: Add instances to global hosts file
    become: true
    lineinfile:
      dest: /etc/ansible/hosts
      insertafter: "[{{ aws_ansible_group_tag }}]"
      regexp: "{{ item.id }}"
      line: "{{ item.id }} ansible_host={{ item.public_ip }} ansible_ssh_user={{ aws_ami_default_user }} ansible_ssh_private_key_file=~/.aws/{{ aws_key }}.pem"
    with_items: "{{ec2.tagged_instances}}"

- name: Configure instances
  hosts: "{{ aws_ansible_group_tag }}"
  become: true
  tags:
  - config
  roles:
  - common
  - webserver
